[deps]
ACEpotentials = "3b96b61c-0fcc-4693-95ed-1ef9f35fcc53"
AtomsCalculators = "a3e0e189-c65a-42c1-833c-339540406eb1"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ExtXYZ = "352459e4-ddd7-4360-8937-99dcb397b478"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
