[deps]
ACEpotentials = "3b96b61c-0fcc-4693-95ed-1ef9f35fcc53"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsBuilder = "f5cc8831-eeb7-4288-8d9f-d6c1ddb77004"
AtomsCalculators = "a3e0e189-c65a-42c1-833c-339540406eb1"
AtomsCalculatorsUtilities = "9855a07e-8816-4d1b-ac92-859c17475477"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ExtXYZ = "352459e4-ddd7-4360-8937-99dcb397b478"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeomOpt = "ca147568-c688-4a55-a13d-dbd284330f4b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plotly = "58dd65bb-95f3-509e-9936-c39a10fdeae7"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ACEpotentials = "0.9.1"
